# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bh_tsne_gradient_cpp <- function(indices, indptr, P_data, embedding, theta = 0.5, eps = 1e-16, n_threads = 1L) {
    .Call(`_smallvis_bh_tsne_gradient_cpp`, indices, indptr, P_data, embedding, theta, eps, n_threads)
}

bh_plogq_cpp <- function(indices, indptr, P_data, embedding, theta = 0.5, eps = 1e-16, n_threads = 1L) {
    .Call(`_smallvis_bh_plogq_cpp`, indices, indptr, P_data, embedding, theta, eps, n_threads)
}

dist2_cpp <- function(input, n_threads = 1L) {
    .Call(`_smallvis_dist2_cpp`, input, n_threads)
}

dist_cpp <- function(input, n_threads = 1L) {
    .Call(`_smallvis_dist_cpp`, input, n_threads)
}

tweight_cpp <- function(input, n_threads = 1L) {
    .Call(`_smallvis_tweight_cpp`, input, n_threads)
}

d2_to_tweight_cpp <- function(dist_matrix, n_threads) {
    .Call(`_smallvis_d2_to_tweight_cpp`, dist_matrix, n_threads)
}

tsne_grad_cpp <- function(P, W, Z, Y, n_threads) {
    .Call(`_smallvis_tsne_grad_cpp`, P, W, Z, Y, n_threads)
}

mmds_grad_cpp <- function(R, D, Y, eps, n_threads) {
    .Call(`_smallvis_mmds_grad_cpp`, R, D, Y, eps, n_threads)
}

find_beta_knn_cpp <- function(knn_distances, knn_indices, perplexity = 15, tol = 1e-5, max_tries = 50L, ret_sparse = FALSE, n_threads = 1L) {
    .Call(`_smallvis_find_beta_knn_cpp`, knn_distances, knn_indices, perplexity, tol, max_tries, ret_sparse, n_threads)
}

find_beta_cpp <- function(X, perplexity = 15, tol = 1e-5, max_tries = 50L, n_threads = 1L) {
    .Call(`_smallvis_find_beta_cpp`, X, perplexity, tol, max_tries, n_threads)
}

