# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist2_cpp <- function(input, n_threads = 1L) {
    .Call(`_smallvis_dist2_cpp`, input, n_threads)
}

dist_cpp <- function(input, n_threads = 1L) {
    .Call(`_smallvis_dist_cpp`, input, n_threads)
}

